name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  quality:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --all-features -- --test-threads=1
      - name: Build documentation
        shell: pwsh
        run: |
          $env:RUSTDOCFLAGS = '-D warnings'
          cargo doc --all-features --no-deps
      - run: cargo package

  msrv:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
      - run: cargo check --all-targets --all-features
      - run: cargo test --all-features -- --test-threads=1
